"""Find the highest mean-logprob-per-token prefix, starting from the very
root of the tree, across a completion_history.json export.

Approach: a token-level trie, built in one pass over every record:
  - walk each record's own PROMPT tokens through the trie, creating nodes as
    needed
  - walk each record's own COMPLETION tokens (choices[0].logprobs) through
    the trie starting from wherever the prompt walk ended, attaching the
    real logprob to each node — AND attaching each step's full
    top_logprobs distribution to the node the walk was standing ON, i.e.
    the possible-next-token table for that exact context

Every prompt in this tool's data was built by truncating some earlier
completion's rendered tokens, so every position that ever appears in
anyone's prompt is, somewhere else in the dataset, also covered by some
record's own completion span — which usually attaches a real logprob
directly. The one case that doesn't: a token picked as a *replacement* via
the tooltip (logprobs.html's "click an alternative" flow) was never the
CHOSEN token of any single API call, so it never appears in anyone's
token_logprobs. But its real logprob was still reported by the model, in
the PARENT node's own top_logprobs distribution (that's exactly what the
tooltip displayed before you clicked it) — the app just never persisted it
onto the child record. A second pass fills exactly these gaps: for every
node with a recorded top_logprobs table, any child token present as a key
in that table gets its logprob filled in from there, even if that child
was otherwise only ever reached via a bare prompt-walk.

Only a genuinely never-scored position (some other, real gap — e.g. a
prompt/tokens pair hand-edited via the raw "object" editor) remains unfilled.

None of this depends on previous_response_id or the best-effort "repair
links" ids field, both of which can be missing, stale, or approximate —
only on exact token-sequence identity, which is always present.

The trie is built separately per model (pass --model): mixing tokens
generated by different models along one "path" wouldn't correspond to
anything any single model actually produced.

Usage:
    python3 best_avg_logprob_path.py completion_history.json
    python3 best_avg_logprob_path.py completion_history.json --model davinci-002
    python3 best_avg_logprob_path.py completion_history.json --min-n 8
    python3 best_avg_logprob_path.py completion_history.json --top 5
    python3 best_avg_logprob_path.py completion_history.json --chosen-only   # old strict behavior
"""

import argparse
import json
from typing import Dict, List, Optional, Tuple


def token_logprob_triples(choice_logprobs: Optional[Dict]) -> List[Tuple[str, float, Dict[str, float]]]:
    """Legacy {tokens, token_logprobs, top_logprobs} or chat {content:[...]} ->
    [(chosen_token, chosen_logprob, {alt_token: alt_logprob, ...}), ...]."""
    if not choice_logprobs:
        return []
    if choice_logprobs.get("content") is not None:
        out = []
        for c in choice_logprobs["content"]:
            alts = {a["token"]: a["logprob"] for a in (c.get("top_logprobs") or [])}
            out.append((c["token"], c["logprob"], alts))
        return out
    toks = choice_logprobs.get("tokens") or []
    lps = choice_logprobs.get("token_logprobs") or []
    tops = choice_logprobs.get("top_logprobs") or []
    out = []
    for i, tok in enumerate(toks):
        lp = lps[i] if i < len(lps) else None
        alts = dict(tops[i]) if i < len(tops) and tops[i] else {}
        out.append((tok, lp, alts))
    return out


class TrieNode:
    __slots__ = ("children", "token", "logprob", "top_logprobs", "source")

    def __init__(self):
        self.children: Dict[str, "TrieNode"] = {}
        self.token: Optional[str] = None
        self.logprob: Optional[float] = None
        self.top_logprobs: Optional[Dict[str, float]] = None
        self.source: Optional[str] = None  # "chosen" | "alt" — how logprob was filled, for transparency


def record_model(rec: Dict) -> str:
    return rec.get("model") or (rec.get("request") or {}).get("model") or ""


def model_matches(rec: Dict, model: str) -> bool:
    """Whether this record answers a request for `model`.

    A substring test against the served name is wrong, and silently: the API
    serves davinci-002 as `davinci:2023-07-21-v2` and babbage-002 as
    `babbage:2023-07-21-v2`, so "davinci-002" appears in neither. Filtering the
    trie that way dropped every davinci and babbage record and the ranking came
    back empty rather than filtered. It only looked right for
    gpt-3.5-turbo-instruct, whose served name does contain the asked name.

    So the request wins where it exists -- it records the name that was asked
    for -- and the served name is a prefix fallback for the older records that
    have no request block.
    """
    asked = (rec.get("request") or {}).get("model")
    if isinstance(asked, str):
        return asked == model
    served = record_model(rec)
    return isinstance(served, str) and served.startswith(model)


def build_trie(records: List[Dict], model_filter: Optional[str] = None) -> TrieNode:
    root = TrieNode()
    for rec in records:
        if model_filter and not model_matches(rec, model_filter):
            continue

        prompt_tokens = ((rec.get("prompt") or {}).get("logprobs") or {}).get("tokens") or []
        own_triples = token_logprob_triples((rec.get("choices") or [{}])[0].get("logprobs"))

        node = root
        for tok in prompt_tokens:
            node = node.children.setdefault(tok, TrieNode())

        for tok, lp, alts in own_triples:
            if alts and node.top_logprobs is None:
                node.top_logprobs = alts
            child = node.children.setdefault(tok, TrieNode())
            if child.logprob is None:
                child.token, child.logprob, child.source = tok, lp, "chosen"
            node = child

    # Second pass: fill any child whose token is a known alternative in its
    # parent's top_logprobs table, even though it was never itself "chosen".
    # Iterative, not recursive: a single 4096-token completion makes the trie
    # 4096 levels deep, well past Python's default recursion limit.
    stack = [root]
    while stack:
        node = stack.pop()
        if node.top_logprobs:
            for tok, child in node.children.items():
                if child.logprob is None and tok in node.top_logprobs:
                    child.token = tok
                    child.logprob = node.top_logprobs[tok]
                    child.source = "alt"
        stack.extend(node.children.values())

    return root


def find_best_prefix(root: TrieNode, min_n: int = 1, top: int = 1, allow_gaps: bool = False,
                      chosen_only: bool = False) -> List[Dict]:
    """DFS from the root, tracking running (sum, n); returns the `top` best prefixes.

    A "gap" is a trie position with no known logprob at all — from neither a
    chosen-token generation nor any recorded top_logprobs alternative. Once a
    path crosses a gap, its running sum no longer reflects an unbroken count
    from the true root, so by default such paths are dropped entirely. Pass
    allow_gaps=True to see everything anyway, at the cost of that guarantee.
    """
    best: List[Dict] = []

    def usable(child: TrieNode) -> bool:
        if child.logprob is None:
            return False
        if chosen_only and child.source != "chosen":
            return False
        return True

    def consider(avg, n, tokens, total, gap_count):
        entry = {"avg": avg, "n": n, "tokens": list(tokens), "sum": total, "gaps": gap_count}
        best.append(entry)
        best.sort(key=lambda e: -e["avg"])
        if len(best) > top:
            best.pop()

    # Iterative DFS with an explicit stack: a single 4096-token completion makes
    # the trie 4096 levels deep, well past Python's default recursion limit.
    stack: List[Tuple[TrieNode, List[str], float, int, int]] = [(root, [], 0.0, 0, 0)]
    while stack:
        node, tokens, cum_sum, n, gap_count = stack.pop()
        for tok, child in node.children.items():
            if not usable(child):
                if allow_gaps:
                    stack.append((child, tokens, cum_sum, n, gap_count + 1))
                continue
            if gap_count and not allow_gaps:
                continue
            new_sum = cum_sum + child.logprob
            new_n = n + 1
            new_tokens = tokens + [child.token]
            if new_n >= min_n:
                avg = new_sum / new_n
                if len(best) < top or avg > best[-1]["avg"]:
                    consider(avg, new_n, new_tokens, new_sum, gap_count)
            stack.append((child, new_tokens, new_sum, new_n, gap_count))

    return best


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("file", help="completion_history.json (array) or a single response object")
    ap.add_argument("--model", help="substring filter on model, e.g. davinci-002")
    ap.add_argument("--min-n", type=int, default=1, help="ignore prefixes shorter than this")
    ap.add_argument("--top", type=int, default=1, help="show the N best prefixes, not just #1")
    ap.add_argument("--allow-gaps", action="store_true",
                     help="also consider paths that cross an unscored position (breaks the "
                          "from-the-true-root guarantee; off by default)")
    ap.add_argument("--chosen-only", action="store_true",
                     help="ignore top_logprobs-recovered alternative tokens; only count tokens "
                          "that were actually the chosen output of some API call")
    args = ap.parse_args()

    data = json.load(open(args.file, encoding="utf-8"))
    records = data if isinstance(data, list) else [data]

    root = build_trie(records, args.model)
    results = find_best_prefix(root, args.min_n, args.top, args.allow_gaps, args.chosen_only)

    if not results:
        raise SystemExit("No scored prefixes found (empty file, or --model matched nothing).")

    for i, r in enumerate(results, 1):
        print(f"#{i}")
        print(f"  n          : {r['n']}")
        print(f"  sum logP   : {r['sum']:.4f}")
        print(f"  mean logP  : {r['avg']:.4f}")
        print(f"  perplexity : {pow(2.718281828459045, -r['avg']):.4f}")
        if r["gaps"]:
            print(f"  gaps hit   : {r['gaps']}  (positions with no known logprob source)")
        print(f"  text       : {''.join(r['tokens'])!r}")
        print()


if __name__ == "__main__":
    main()
